name: Integration Test opensearch-cli
on:
  push:
    branches:
      - main
      - opensearch-*
  pull_request:
    branches:
      - main
      - opensearch-*

jobs:
  integ-test:
    strategy:
      matrix:
        entry:
          - { opensearch_version: 1.0.1 }
          - { opensearch_version: 1.1.0 }
          - { opensearch_version: 1.2.4 }
          - { opensearch_version: 1.3.8 }
          - { opensearch_version: 2.0.1 }
          - { opensearch_version: 2.1.0 }
          - { opensearch_version: 2.2.1 }
          - { opensearch_version: 2.3.0 }
          - { opensearch_version: 2.4.1 }
          - { opensearch_version: 2.5.0 }
          - { opensearch_version: 2.6.0 }
          - { opensearch_version: 2.7.0 }
          - { opensearch_version: 2.8.0 }
          - { opensearch_version: 2.9.0 }
          - { opensearch_version: 2.10.0 }
          - { opensearch_version: 2.11.0 }
        go-version: [ 1.18.2 ]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out source code
        uses: actions/checkout@v3

      - name: Run Docker Image
        env:
          OPENSEARCH_VERSION: ${{ matrix.opensearch-version }}
        run: |
          make docker.start.components
          sleep 60

      - name: Run Integration Tests
        env:
          GOPROXY: "https://proxy.golang.org"
        run: make test.integration


      - name: Stop and Clean Docker Components
        run: |
          make docker.stop
          make docker.clean
